---
# This default profile is used when running a single instance completely standalone:
server:
  port: 8761  
eureka:
  instance:
    hostname: localhost  
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
---
spring:
  profiles: dev
server:
  port: 8761   
eureka:
  instance:
    hostname: 192.168.99.100
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/                 
      